import { describe, expect, it } from "bun:test";
import { tryUnwrapEmbeddedHtml } from "../../../src/core/knowledge/unwrap-embedded-html";

describe("tryUnwrapEmbeddedHtml — class signal tier", () => {
  it("unwraps a textarea with class containing 'wiki-code' carrying HTML", () => {
    const inner = `<html><body><h2>Heading</h2><p>${'word '.repeat(150)}</p></body></html>`;
    const outer = `<html><body>
      <div class="header">chrome</div>
      <textarea class="wiki-code" rows="25" cols="80">${inner}</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("Heading");
    expect(r).toContain("<h2>");
  });

  it("unwraps a textarea whose inner content has a leading HTML comment", () => {
    const inner = `<!-- DO NOT change. Generated by some tool. -->\n<html><body><h2>Title</h2><p>${'word '.repeat(150)}</p></body></html>`;
    const outer = `<html><body>
      <textarea class="wiki-code">${inner}</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("Title");
  });

  it("unwraps a pre with class containing 'source-code'", () => {
    const inner = `<html><body>${'<p>x</p>'.repeat(60)}</body></html>`;
    const outer = `<html><body><pre class="source-code lang-html">${inner}</pre></body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("<p>x</p>");
  });

  it("unwraps a script type='text/template' with embedded HTML", () => {
    const inner = `<html><body><h1>Embedded</h1><p>${'word '.repeat(150)}</p></body></html>`;
    const outer = `<html><body><script type="text/template" class="embedded-content">${inner}</script></body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("Embedded");
  });
});

describe("tryUnwrapEmbeddedHtml — shape fallback tier", () => {
  it("unwraps a textarea with no recognised class, when inner content dominates the page", () => {
    const inner = `<html><body><h2>Major content</h2>${'<p>word</p>'.repeat(200)}</body></html>`;
    const outer = `<html><body>
      <div>tiny chrome</div>
      <textarea>${inner}</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("Major content");
  });

  it("does NOT unwrap a textarea whose content is small (chrome-shaped)", () => {
    const outer = `<html><body>
      <article><h1>Real article</h1>${'<p>word</p>'.repeat(100)}</article>
      <textarea>just a comment box, 25 chars</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).toBeNull();
  });

  it("does NOT unwrap a textarea whose content is similar in size to outer body", () => {
    // Inner is HTML but only 1.5x outer (below the 2x threshold).
    const inner = `<html><body><p>${'inner '.repeat(80)}</p></body></html>`;
    const outer = `<html><body>
      <article>${'<p>outer body word with substantial content</p>'.repeat(40)}</article>
      <textarea>${inner}</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).toBeNull();
  });
});

describe("tryUnwrapEmbeddedHtml — non-cases", () => {
  it("returns null when no embedded content elements exist", () => {
    const html = `<html><body><h1>Plain article</h1>${'<p>word</p>'.repeat(50)}</body></html>`;
    expect(tryUnwrapEmbeddedHtml(html)).toBeNull();
  });

  it("returns null when textarea content is plain text (not HTML)", () => {
    const outer = `<html><body><textarea class="wiki-code">${'word '.repeat(200)}</textarea></body></html>`;
    expect(tryUnwrapEmbeddedHtml(outer)).toBeNull();
  });

  it("returns null when textarea content is small even with class signal", () => {
    const outer = `<html><body><textarea class="wiki-code"><html><body>tiny</body></html></textarea></body></html>`;
    expect(tryUnwrapEmbeddedHtml(outer)).toBeNull();
  });

  it("class signal beats shape fallback when both apply", () => {
    // The class-marked element has smaller content than another textarea on
    // the page, but class signal wins.
    const inner = `<html><body><h2>Class-marked</h2><p>${'word '.repeat(120)}</p></body></html>`;
    const outer = `<html><body>
      <textarea class="wiki-code">${inner}</textarea>
      <textarea>${'<html><body>'+'<p>shape</p>'.repeat(300)+'</body></html>'}</textarea>
    </body></html>`;
    const r = tryUnwrapEmbeddedHtml(outer);
    expect(r).not.toBeNull();
    expect(r).toContain("Class-marked");
    expect(r).not.toContain("shape");
  });

  it("handles malformed HTML gracefully (returns null, doesn't throw)", () => {
    expect(tryUnwrapEmbeddedHtml("<html><body><textarea")).toBeNull();
    expect(tryUnwrapEmbeddedHtml("")).toBeNull();
    expect(tryUnwrapEmbeddedHtml("plain text")).toBeNull();
  });
});
