/** Render the agent-smith-refresh OpenCode plugin TypeScript source.
 *  Deterministic — call multiple times for byte-identical output. */
export function renderOpencodePlugin(): string {
  return `// agent-smith-refresh plugin
// Auto-generated by 'smith agent install' — do not edit by hand.
// Listens on session.created and shells out to smith knowledge refresh-session
// with a 5s timeout. Soft-fails on any error.

export default function plugin({ $ }: { $: any }) {
  return {
    "session.created": async () => {
      try {
        await $\`smith knowledge refresh-session --platform opencode\`.timeout(5000);
      } catch (err: any) {
        // soft-fail: log to opencode + smith log, never throw
        console.error("smith: refresh failed:", err?.message ?? String(err));
      }
    },
  };
}
`;
}
